### ISSUE TITLE
Fail to start subsquid-processor

### ISSUE THREAD

**Issue by rfabriciors** [reef-chain/subsquid-processor#8]
Hello everyone, I tried to start the subsquid processor through the instructions but I got the message 'REEF verified contract not found in database' as soon as the 'make process' step was completed. I checked if the 'verified_contract' tables were created and yes, they are there. I had no issues or errors during the initial setup. Has anyone experienced this problem?

```bash
node -r dotenv/config lib/processor.js

NETWORK= mainnet  RPC= ws://substrate-node:9944/ws  AQUARIUM_ARCHIVE_NAME= reef
Pusher enabled: true
Head reached: false
Pin to IPFS: true
17:56:59 INFO  sqd:processor processing blocks from 0
17:56:59 INFO  sqd:processor prometheus metrics are served at port 3001
17:57:00 FATAL sqd:processor Error: REEF verified contract not found in the database
                                 at /opt/subsquid-processor/lib/processor.js:75:19
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async TypeormDatabase.runTransaction (/opt/subsquid-processor/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)
                                 at async TypeormDatabase.transact (/opt/subsquid-processor/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
                                 at async Runner.process (/opt/subsquid-processor/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)
```

**Comment by boo-0x** [comment]
Hi @rfabriciors. 
The contract should be inserted by the same script that creates the tables, so not sure what the problem might be. 

https://github.com/reef-chain/subsquid-processor/blob/4de21b7097845ce32b18c391a2aff3c37e247a03/db/migrations/1695194382416-Data.js#L333

In any case, if you are creating your own Squid, I recommend you using this template and process only the data you need:
https://github.com/reef-chain/subsquid-evm-event-processor. Note that the Subsquid team has released a new version (ArrowSquid) and we are in the process of migrating both the template and this project. We expect the change to be finished in the following weeks, but you can still start with current version and migrate later with the new changes.

**Comment by rfabriciors** [comment]
Hello everyone, thank you very much for your help. We managed to start our explorer. Thank you for your help.
